depth_image_preprocessor_node:
  ros__parameters:
    input:
      topic: /camera/depth/image_rect_raw
      width: 212
      height: 120
      depth_scale_16uc1: 0.001
      camera_info:
        topic: /camera/depth/camera_info
        # calibrated 848x480 stream after decimation factor 4: [fx, fy, cx, cy].
        intrinsics: [107.55355072021475, 107.55355072021475, 106.8992919921875, 59.2901763916015]
        intrinsics_atol: 0.001
        distortion_model: plumb_bob
        distortion: [0.0, 0.0, 0.0, 0.0, 0.0]
        distortion_atol: 1.0e-9
    output:
      topic: /unitree_go2_beam_depth/depth_m

    # The ONNX graph performs clipping and normalization.
    process_order: [replace_invalid]
    replace_invalid:
      valid_min: 0.0
      valid_min_inclusive: true
      value: 0.0
